In [1]:
#新建一个CSV文件
import os
os.makedirs(os.path.join('..','test-data'),exist_ok=True)
data_file = os.path.join('..', 'test-data','house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') #列名
    f.write('NA,Pave,127500\n') #每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [4]:
#打开CSV文件进行操作
import pandas as pd
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       4.0   NaN  178100
4       NaN   NaN  140000

In [5]:
#为了处理缺失的数据，典型的方法包括 插值和删除
#使用插值的方法, iloc=index location
#fillna = 在not a number的地方填上值
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0  3.333333  Pave
1  2.000000   NaN
2  4.000000   NaN
3  4.000000   NaN
4  3.333333   NaN


C:\Users\PC\anaconda3\envs\python3_7_cpu\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.


In [6]:
#对于inputs中的类别值或者离散值，我们将“NaN”视为一个类别
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0  3.333333           1          0
1  2.000000           0          1
2  4.000000           0          1
3  4.000000           0          1
4  3.333333           0          1


In [7]:
#现在inputs和outputs中的所有条目都是数值类型，它们可以转换为张量格式
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3.3333, 1.0000, 0.0000],
         [2.0000, 0.0000, 1.0000],
         [4.0000, 0.0000, 1.0000],
         [4.0000, 0.0000, 1.0000],
         [3.3333, 0.0000, 1.0000]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 178100, 140000]))

In [8]:
#使用reshape只是创建了一个view，并没有创建一个新的张量
#example：改b的时候把a改了
#最好不用对数组进行过多的操作
a = torch.arange(12)
b = a.reshape((3,4))
b[:] = 2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])