In [1]:
import torch

x = torch.arange(12)
x.shape #访问张量的形状
x.numel() #访问张量的元素数量

12

In [2]:

X = x.reshape(3, 4) #改变张量的形状而不改变元素数量和元素值
print(X)

print(torch.zeros((2, 3, 4))) #创建全0的tensor
print(torch.ones((2, 3, 4)))  #创建全1的tensor

y = torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]]) #通过提供包含数值的Python列表来为所需张量中的每个元素赋予确定值
print(y.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([1, 3, 4])


In [3]:
# 常见的标准算术运算符（+、-、*、/和**）：按元素运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [4]:
#按元素方式应用更多的计算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [5]:
#cat用于把多个张量连结到一起，dim指维度。dim为0指在行层面合并，dim为1指在列层面合并
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y =torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [6]:
#通过逻辑运算符构建二位张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [7]:
#对张量中的所有元素进行求和会产生只有一个元素的张量
X.sum()

tensor(66.)

In [9]:
#广播机制按元素操作
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [10]:
# 元素的访问
#-1 访问最后一行，1：3表示把第一行到第二行拿出来
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [11]:
#为多个元素赋值相同的值
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [12]:
#在python中运行一些操作可能会导致为新结果分配内存，导致之前的内存被析构了
#id相当于c++中的指针运算符
before = id(Y)
Y = Y + X
id(Y) == before

False

In [14]:
#执行原地操作
#torch.zeros_like函数创建一个维度一样形状一样的数组，但是全赋值为0
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1458391068328
id(Z): 1458391068328


In [15]:
#类型转换
#转换为Numpy张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [16]:
#将大小为1的张量转换为Python张量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)