In [1]:
import torch
import torch.nn.functional as F
from torch import nn

# 自定义层

In [2]:
# 构造一个没有任何此参数的自定义层
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
# 将层作为组件合并到构建更复杂的模型中
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-1.3970e-09, grad_fn=<MeanBackward0>)

In [6]:
#带参数的图层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
    
dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[ 0.0416, -0.1499, -0.7751],
        [-0.2488, -2.1221, -0.3790],
        [ 1.0881, -0.7904, -1.5035],
        [ 0.1152, -0.5143, -2.3903],
        [ 0.8116,  0.2013, -0.1503]], requires_grad=True)

In [7]:
#使用自定义层直接执行正向传播计算
dense(torch.rand(2, 5))

tensor([[0.6597, 0.0000, 0.0000],
        [1.1066, 0.0000, 0.0000]])

In [8]:
#使用自定义层构建模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[ 9.2255],
        [13.4908]])